Нужно больше функций
htmlacademy-javascript/1725199-kekstagram-23 pull request #2
Opened 2021-06-07 13:01 UTC by Svetlana-Saloa

2021-06-07 16:59 UTC, polina-prokofieva requested changes
Для первого раза неплохо, но есть несколько замечайний.

2021-06-07 16:59 UTC, polina-prokofieva commented on js/main.js
> +  min >= 0;
Какой смысл в этой строке?
Она ничего не делает, её можно и нужно убрать.

2021-06-07 16:59 UTC, polina-prokofieva commented on js/main.js
> +randomNumer();
Тут, кажется, не хвататет параметров.
Есть несколько вариантов (можно реализовать любой, на выбор):
1. Оставить, как есть, чтобы линт не ругался. Но тогда надо сделать так, чтобы функция работала, если нет аргументов.
2. Вызвать функцию с аргументами.
3. Сделать в функции значения по умолчанию для аргументов.

2021-06-07 16:59 UTC, polina-prokofieva commented on js/main.js
> +commentsSize();
Тут аналогично, как и с первой функцией.

2021-06-07 16:59 UTC, polina-prokofieva commented on js/main.js
> +    (checkedString>maxLength);
Бессмысленная строка.

2021-06-07 16:59 UTC, polina-prokofieva commented on js/main.js
> +  }
Этот код нужно упростить, как показано в примере: [Критерий 18](https://up.htmlacademy.ru/javascript/23/criteries#d18)

2021-06-08 11:15 UTC, polina-prokofieva requested changes

2021-06-08 11:15 UTC, polina-prokofieva commented on js/main.js
> +function randomNumer(min, max) {
Эту функцию лучше назвать getRandomNumber ([Критерий Б6](https://up.htmlacademy.ru/javascript/23/criteries#b6))

2021-06-08 11:15 UTC, polina-prokofieva commented on js/main.js
> +function commentsSize(checkedString, maxLength) {
Эту функцию лучше назвать checkCommentSize ([Критерий Б6](https://up.htmlacademy.ru/javascript/23/criteries#b6))

2021-06-08 11:15 UTC, polina-prokofieva commented on js/main.js
> +  return checkedString<=maxLength;
Тут сравнение строки с числом - такое сравнение не имеет никакого смысла. Нужно сравнивать не саму строку, а длину строки. То есть правильно будет так:
```
checkedString.length <= maxLength
```

2021-06-08 11:15 UTC, polina-prokofieva commented on js/main.js
> +commentsSize('some_string',140);
Чтобы проверить правильно ли работает функция, можно результат её вызовы выводить в консоль.
```
console.log(commentsSize('some_string',140));
```
Главное, не забывать этот `console.log` потом убирать перед коммитом. Просто эта функция работает сейчас не правильно и важно, чтобы ты умела это проверять.

2021-06-08 12:39 UTC, Svetlana-Saloa commented on js/main.js
> +commentsSize('some_string',140);
консоль написала true, значит работает))?!

2021-06-08 13:14 UTC, polina-prokofieva approved these changes

2021-06-08 13:14 UTC, merged